In [40]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_classification

In [41]:
from sklearn.metrics import precision_score, recall_score, roc_auc_score, roc_curve
import matplotlib.pyplot as plt

In [42]:
test_error=[]

for i in range(3): 
    name='y_train'+str(i)+'.npy'
    y_train = np.load(name).reshape(-1)
    name='X_train_'+str(i) +'.npy'
    x_train = np.load(name).reshape(len(y_train),-1)
    model = RandomForestRegressor(n_estimators=100, bootstrap = False,
                               max_features = 'sqrt')
    model.fit(x_train, y_train)
    name='y_test_'+str(i) +'.npy'
    y_test = np.load(name).reshape(-1)
    name='X_test_'+str(i) +'.npy'
    x_test = np.load(name).reshape(len(y_test),-1)
    y_hat=model.predict(x_test)
    print(y_hat)
    
    error=(np.sum(((y_test[y_test!=0]-y_hat[y_test!=0])/y_test[y_test!=0])**2)/len(y_hat[y_test!=0]))**-2
    test_error=[test_error,error]
         

[ 5019.15  6185.16  8841.68 ...  7125.55  7706.89 11664.97]
[5138.77 6896.26 7759.16 ... 5467.7  8350.79 5485.42]
[6710.6  4708.9  4044.31 ... 5765.4  9168.35 6763.72]


In [43]:
test_error

[[[[], 9000.559172618125], 26265.17822567658], 7947.266362018224]

In [44]:
np.save('random_forest_regression_errors', test_error)