In [1]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_classification

/home/edith/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
from sklearn.metrics import precision_score, recall_score, roc_auc_score, roc_curve
import matplotlib.pyplot as plt

In [30]:
test_error=[]

for i in range(3): 
    name='y_train'+str(i)+'.npy'
    y_train = np.load(name).reshape(-1)
    name='X_train_'+str(i) +'.npy'
    x_train = np.load(name).reshape(len(y_train),-1)
    model = RandomForestRegressor(n_estimators=100, bootstrap = False,
                               max_features = 'sqrt')
    model.fit(x_train, y_train)
    name='y_test_'+str(i) +'.npy'
    y_test = np.load(name).reshape(-1)
    name='X_test_'+str(i) +'.npy'
    x_test = np.load(name).reshape(len(y_test),-1)
    y_hat=model.predict(x_test)
    print(y_hat)
    
    error=(np.sum(((y_test[y_test!=0]-y_hat[y_test!=0])/y_test[y_test!=0])**2)/len(y_hat[y_test!=0]))**-2
    test_error=[test_error,error]
         

[ 6403.4  6417.2 10079.2 ...  7192.4  7137.  11336.6]
[5484.6 5929.2 8230.  ... 5337.4 6320.  4964.8]
[6604.  4531.2 6476.8 ... 6067.2 8018.4 7477.2]


In [31]:
test_error

[[[[], 596.1806384077207], 555.2418561897881], 405.9157964166307]

In [29]:
x_test.shape

(288209, 10)